/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.ejemplo;

import java.util.LinkedList;
import java.util.Queue;
import javax.swing.JOptionPane;

/**
 *
 * @author SCIA-PC15
 */
public class Cola extends javax.swing.JFrame {
Queue<String> lista = new LinkedList<>();
    /**
     * Creates new form NewJFrame
     */
    public Cola() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        agregarCola = new javax.swing.JButton();
        eliminarCola = new javax.swing.JButton();
        consultar = new javax.swing.JButton();
        quienSigue = new javax.swing.JButton();
        esVacia = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Ejemplo de cola");

        agregarCola.setText("Cliente nuevo");
        agregarCola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarColaActionPerformed(evt);
            }
        });

        eliminarCola.setText("Atender cliente");
        eliminarCola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarColaActionPerformed(evt);
            }
        });

        consultar.setText("Consultar");
        consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarActionPerformed(evt);
            }
        });

        quienSigue.setText("Ver cliente que sigue");
        quienSigue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quienSigueActionPerformed(evt);
            }
        });

        esVacia.setText("Esta vacia");
        esVacia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                esVaciaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(eliminarCola)
                            .addComponent(agregarCola))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(quienSigue)
                            .addComponent(consultar)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(jLabel1)))
                .addContainerGap(11, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addComponent(esVacia)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel1)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(agregarCola)
                    .addComponent(quienSigue))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eliminarCola)
                    .addComponent(consultar))
                .addGap(18, 18, 18)
                .addComponent(esVacia)
                .addContainerGap(81, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void agregarColaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarColaActionPerformed
       String elemento = JOptionPane.showInputDialog("Ingrese el nombre del elemento");
      lista.add(elemento);
    }//GEN-LAST:event_agregarColaActionPerformed

    private void eliminarColaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarColaActionPerformed
        JOptionPane.showMessageDialog(null, "Cliente atendido: "+lista.peek());
        lista.poll();
    }//GEN-LAST:event_eliminarColaActionPerformed

    private void consultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarActionPerformed

        JOptionPane.showMessageDialog(null, "Los elementos de la lista son: " + lista );
    }//GEN-LAST:event_consultarActionPerformed

    private void quienSigueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quienSigueActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "El siguente cliente es: "+lista.peek());
    }//GEN-LAST:event_quienSigueActionPerformed

    private void esVaciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_esVaciaActionPerformed
        // TODO add your handling code here:
        if(lista.isEmpty() == true){
            JOptionPane.showMessageDialog(null, "No hay clientes en la lista");
        } else {
            JOptionPane.showMessageDialog(null, "Hay mas clientes por atender");
        }
    }//GEN-LAST:event_esVaciaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cola().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarCola;
    private javax.swing.JButton consultar;
    private javax.swing.JButton eliminarCola;
    private javax.swing.JButton esVacia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton quienSigue;
    // End of variables declaration//GEN-END:variables
}
